import { DataDetail } from "@src/components";
import { DATA } from "@src/utils/data";
import Head from "next/head";

function ContentDetailPage({ ...props }) {
    const {
        contentDetail, contentList
    } = props;

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>


                <DataDetail data={contentDetail} />

                <div>
                    {JSON.stringify(contentList)}
                </div>

            </main>
        </>
    )

}

export async function getStaticProps({ params }) {
    const contentDetail = DATA.find((item) => item.id === +params.id);

    if (contentDetail) {
        const contentList = DATA.filter(
            (item) => item.id !== +params.id
        );
        return {
            props: {
                contentDetail,
                contentList,
            },
        };
    } else {
        return { props: {} };
    }
}

export async function getStaticPaths() {
    const paths = DATA.map((item) => `/tam-tinh/${item.id}`);

    return {
        paths,
        fallback: "blocking",
    };
}

export default ContentDetailPage;
